[project]
name = "user-service"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Sayantan Saha", email = "sayantansaha11187@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "fastapi[standard]>=0.141.1",
    "psycopg[binary]>=3.3.6",
    "sqlalchemy>=2.0.54",
    "sqlmodel>=0.0.47",
]

[project.scripts]
user-service = "user_service:main"

[build-system]
requires = ["uv_build>=0.11.7,<0.12.0"]
build-backend = "uv_build"
